name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Test Linux ARM64
      run: |
        nix build .#cursor.linux.arm64-targz
        file result/*
        nix build .#cursor.linux.arm64-appimage
        file result/*
        rm -rf result

    - name: Test Linux ARM32 builds
      run: |
        nix build .#cursor.linux.arm32-targz
        file result/*
        nix build .#cursor.linux.arm32-appimage
        file result/*
        rm -rf result

    - name: Test Windows ARM64 build
      run: |
        nix build .#cursor.windows.arm64-zip
        file result/*
        rm -rf result

    - name: Test Nix build
      run: |
        nix build .#cursor.nix
        cd result && ls -alh
